# Generated by Django 4.2.19 on 2025-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_mediaresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
